### ISSUE TITLE
Anno Auswertung: Timestamps in die Auswertungstabelle

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/annotationsDB-frontend#29]
In der Auswertungstabelle von AnnoDB --> Anno Auswertung wäre es super, wenn Antworten, die ein Token oder Tokenset sind, die zugehörigen Timestamps, wann in der Aufnahme sie vorkommen als Spalte in der Auswertungstabelle dabei haben könnten. Die start_time und end_time vom jeweiligen Event, in dem die Token vorkommen, reichen dabei vollkommen (falls es einfacher ist, reicht auch nur die Startzeit des jeweiligen Events, das ist eventuell für die Tokensets auch leichter).

**Comment by hcb79** [comment]
Gehört eigentlich in https://github.com/german-in-austria/dioeDB ...
